const char ECU_HOMEPAGE[] PROGMEM = R"=====css(
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>APsystems ECU</title><link rel="icon" href="/favicon.ico"><link rel="stylesheet" href="/STYLESHEET"></head>
<body><header class="topbar"><a class="brand" href="/">APsystems ECU</a><nav class="nav"><a class="button secondary" href="/ENERGY">Energy history</a><a class="button secondary" href="/MENU">Menu</a></nav></header>
<main class="page"><section class="hero"><div class="eyebrow">Solar production</div><h1>Your microinverter fleet</h1><p id="statusText">Loading the latest cached telemetry…</p>
<div class="metrics"><div class="metric"><strong id="totalPower">—</strong><span>Current output</span></div><div class="metric"><strong id="todayEnergy">—</strong><span>Energy today</span></div><div class="metric"><strong id="lifetimeEnergy">—</strong><span>Recorded energy</span></div></div></section>
<section><div class="card-head"><div><div class="eyebrow">Inverters</div><h2>Current status</h2></div><span class="badge" id="pollBadge">Loading</span></div><div id="inverters" class="card-grid"><div class="card empty">Loading inverter data…</div></div></section>
</main><script>
const q=s=>document.querySelector(s),fmt=(n,d=1)=>Number(n).toFixed(d),safe=n=>Number.isFinite(Number(n));
function statusBadge(ok,text){return `<span class="badge ${ok?'':'warn'}">${text}</span>`}
function inverterCard(n){let panels=(n.p||[]).map((p,i)=>`<div class="panel-power"><span class="muted">Panel ${i+1}</span><br><strong>${safe(p)?fmt(p)+' W':p}</strong></div>`).join('');return `<article class="card"><div class="card-head"><div><div class="eyebrow">Inverter ${n.index+1}</div><h2>${n.name||'Unnamed inverter'}</h2></div>${statusBadge(n.polled,n.polled?'Online':'No recent data')}</div><dl class="kv"><dt>Current output</dt><dd>${safe(n.power_total)?fmt(n.power_total)+' W':'—'}</dd><dt>Today</dt><dd>${fmt(n.today_wh/1000,3)} kWh</dd><dt>Current hour</dt><dd>${fmt(n.current_hour_wh/1000,3)} kWh</dd><dt>Firmware</dt><dd>${n.firmware||'unknown'}</dd><dt>Transport</dt><dd>${n.encrypted?'AES encrypted':'Plain'}</dd></dl><div class="panel-powers">${panels}</div><div class="actions"><a class="button secondary" href="/details?inv=${n.index}">Details</a><a class="button secondary" href="/ENERGY?inv=${n.index}">History</a></div></article>`}
async function refresh(){try{let general=await fetch('/get.Data?General=1',{cache:'no-store'}).then(r=>r.json());let rows=await Promise.all(Array.from({length:general.cnt},(_,i)=>fetch('/get.Data?Power=0&inv='+i,{cache:'no-store'}).then(r=>r.json())));rows.forEach((r,i)=>r.index=i);q('#inverters').innerHTML=rows.length?rows.map(inverterCard).join(''):'<div class="card empty">No inverters configured. Open Menu → Inverters to add one.</div>';let watts=rows.reduce((s,r)=>s+(safe(r.power_total)?Number(r.power_total):0),0),today=rows.reduce((s,r)=>s+Number(r.today_wh||0),0),life=rows.reduce((s,r)=>s+Number(r.lifetime_wh||0),0);q('#totalPower').textContent=fmt(watts)+' W';q('#todayEnergy').textContent=fmt(today/1000,3)+' kWh';q('#lifetimeEnergy').textContent=fmt(life/1000,3)+' kWh';let ready=general.time_valid&&general.location_valid,mode=general.daylight_polling?(ready?(general.sl?'Night pause':'Daylight polling'):'24-hour fallback'):'24-hour polling';q('#pollBadge').textContent=general.polling?`Auto · ${general.poll_interval}s`:'Manual';q('#pollBadge').className='badge '+(general.polling?'':'warn');q('#statusText').textContent=`${mode}. ${general.time_valid?general.local_time:'Local time unavailable'} · Radio ${general.st==1?'ready':'not ready'}.`;}catch(e){q('#statusText').textContent='The ECU did not return valid telemetry. Retrying…';q('#pollBadge').textContent='Unavailable';q('#pollBadge').className='badge bad'}}
refresh();setInterval(refresh,30000);if(window.EventSource){const e=new EventSource('/events');e.onmessage=()=>refresh()}
</script></body></html>
)=====css";
