const char DETAILSPAGE[] PROGMEM = R"=====(
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Inverter details · APsystems ECU</title><link rel="icon" href="/favicon.ico"><link rel="stylesheet" href="/stylesheet"></head>
<body><header class="topbar"><a class="brand" href="/">APsystems ECU</a><nav class="nav"><a class="button secondary" href="/inverters">Inverters</a><a class="button secondary" href="/menu">Menu</a></nav></header><main class="page"><div class="eyebrow">Live inverter telemetry</div><div class="card-head"><div><h1 id="name">Inverter details</h1><p id="identity">Loading...</p></div><span id="state" class="badge">Loading</span></div>
<div class="metrics"><div class="metric"><strong id="power">&mdash;</strong><span>Current output</span></div><div class="metric"><strong id="today">&mdash;</strong><span>Energy today</span></div><div class="metric"><strong id="life">&mdash;</strong><span>Lifetime Energy</span></div></div>
<div class="card-grid section"><section class="card"><h2>Inverter</h2><dl class="kv"><dt>Model</dt><dd id="model">&mdash;</dd><dt>Firmware</dt><dd id="firmware">unknown</dd><dt>Network ID</dt><dd id="sid">&mdash;</dd><dt>Transport</dt><dd id="transport">&mdash;</dd><dt>Last response</dt><dd id="last">Not yet</dd></dl></section><section class="card"><h2>AC output</h2><dl class="kv"><dt>Voltage</dt><dd id="acv">&mdash;</dd><dt>Frequency</dt><dd id="freq">&mdash;</dd><dt>Temperature</dt><dd id="temp">&mdash;</dd><dt>Signal quality</dt><dd id="signal">&mdash;</dd></dl></section></div>
<section class="section"><div class="card-head"><h2>PV inputs</h2><span class="muted">Only physical inputs for this model are shown.</span></div><div id="panels" class="card-grid"><div class="card empty">Waiting for telemetry...</div></div></section>
<section class="form-card section"><h2>Output limit</h2><p>Set the inverter throttle target. Leave at 0 for normal unrestricted operation.</p><form method="get" action="/inverter/throttle"><input type="hidden" id="inv" name="INV"><div class="field"><label for="limit">Throttle target</label><input id="limit" name="pMax" type="number" min="0" max="500" step="20"></div><div class="actions"><button type="submit">Save limit</button><a class="button secondary" href="/">Cancel</a></div></form></section>
</main><script>
const params=new URLSearchParams(location.search),index=Number(params.get('inv')||0),el=id=>document.getElementById(id),val=(v,u='')=>Number.isFinite(Number(v))?Number(v).toFixed(1)+u:'—';
async function load(){try{let n=await fetch('/api/data?Inverter='+index,{cache:'no-store'}).then(r=>r.json()),types=['YC600','QS1','DS3'];el('name').textContent=n.name||'Inverter '+(index+1);el('identity').textContent='Inverter '+(index+1)+' · Serial '+n.serial;el('state').textContent=n.sid==='0000'?'Not paired':(n.polled?'Online':'No recent data');el('state').className='badge '+(n.polled?'':'warn');el('power').textContent=val(n.pw_total,' W');el('today').textContent=(Number(n.today_wh||0)/1000).toFixed(3)+' kWh';el('life').textContent=(Number(n.lifetime_wh||0)/1000).toFixed(3)+' kWh';el('model').textContent=types[n.type]||'Unknown';el('firmware').textContent=n.firmware||'unknown';el('sid').textContent=n.sid;el('transport').textContent=n.encrypted?'AES encrypted':'Plain (not encrypted)';el('last').textContent=n.last_success||'Not yet';el('acv').textContent=val(n.acv,' V');el('freq').textContent=val(n.freq,' Hz');el('temp').textContent=val(n.temp,' °C');el('signal').textContent=val(n.sq,' %');el('inv').value=n.inv;el('limit').value=n.pwMax;let count=n.panel_count||2;el('panels').innerHTML=Array.from({length:count},(_,i)=>`<article class="card"><div class="eyebrow">Panel ${i+1}</div><h2>${val(n.pow[i],' W')}</h2><dl class="kv"><dt>DC voltage</dt><dd>${val(n.dcv[i],' V')}</dd><dt>DC current</dt><dd>${val(n.dcc[i],' A')}</dd><dt>Recorded energy</dt><dd>${val(n.en[i],' kWh')}</dd></dl></article>`).join('')}catch(e){el('state').textContent='Unavailable';el('state').className='badge warn'}}
load();setInterval(load,30000);
</script></body></html>
)=====";
